apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "guardgress.clusterRole" . }}
  labels:
    {{- include "guardgress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["services","secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses",]
    verbs: ["get", "watch", "list"]