apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardgress-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardgress-cr
rules:
- apiGroups: [""]
  resources: ["services","secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses",]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guardgress-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guardgress-cr
subjects:
- kind: ServiceAccount
  name: guardgress-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guardgress-ingress-controller
  name: guardgress-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardgress-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guardgress-ingress-controller
    spec:
      serviceAccountName: guardgress-sa
      containers:
      # TODO: Provide specific version
      - image: ghcr.io/h3adex/guardgress:latest
        name: guardgress
        env:
        - name: PORT
          value: "80"
        - name: TLS_PORT
          value: "443"
        - name: HOST
          value: "0.0.0.0"
        - name: GIN_MODE
          value: "release"
        - name: LOG_LEVEL
          value: "info"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: guardgress-svc
  name: guardgress-svc
spec:
  type: LoadBalancer
  # This is needed if you want to use the limit-ip annotation
  # More information is available here: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Local
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: guardgress-ingress-controller

