apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guardgress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guardgress
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 50

