apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardgress-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardgress-cluster-role
rules:
  - apiGroups: [""]
    resources: ["services","secrets","endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses",]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guardgress-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guardgress-cluster-role
subjects:
  - kind: ServiceAccount
    name: guardgress-sa
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: guardgress
  namespace: default
  labels:
    app: guardgress
spec:
  selector:
    matchLabels:
      app: guardgress
  template:
    metadata:
      labels:
        app: guardgress
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: guardgress-sa
      containers:
        # TODO: Provide specific version
        - image: ghcr.io/h3adex/guardgress:latest
          name: guardgress
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "80"
            - name: TLS_PORT
              value: "443"
            - name: HOST
              value: "0.0.0.0"
            - name: GIN_MODE
              value: "production"
            - name: LOG_LEVEL
              value: "info"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
