apiVersion: v1
kind: ServiceAccount
metadata:
  name: phalanx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["services","secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses",]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: phalanx
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: phalanx
  namespace: default
  labels:
    app: phalanx
spec:
  selector:
    matchLabels:
      app: phalanx
  template:
    metadata:
      labels:
        app: phalanx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: phalanx
      containers:
        - name: phalanx
          image: ghcr.io/h3adex/phalanx:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
