replicaCount: 1

image:
  repository: ghcr.io/h3adex/guardgress
  pullPolicy: IfNotPresent
  tag: "1.0.0-alpha"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "guardgress-sa"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  httpPort: 80
  httpsPort: 443
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 5

env:
  - name: PORT
    value: "80"
  - name: TLS_PORT
    value: "443"
  - name: LOG_LEVEL
    value: "INFO"

resources:
  limits:
     cpu: 100m
     memory: 256Mi
  requests:
     cpu: 50m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
