apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    "guardgress/user-agent-blacklist": "curl/7.64.1,curl/7.64.2"
    "guardgress/ja3-blacklist": "d41d8cd98f00b204e9800998ecf8427a"
    "guardgress/ja4-blacklist": "t13d1715h2_5b57614c22b0_93c746dc12af"
    "guardgress/limit-ip-whitelist": "127.0.0.1,127.0.0.2"
  name: whoami
  namespace: default
spec:
  ingressClassName: guardgress
  rules:
    - host: whoami.local
      http:
        paths:
          - backend:
              service:
                name: whoami
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - localhost
      secretName: ingress-tls