name: Go-Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-go-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install Dependencies
        run: go get -v -t -d ./...

      - name: Test Go Code
        run: go test -cover ./pkg/...
