name: Tests

on:
  push:
    branches:
      - main
      - dev
      - 'dependabot/**'

jobs:
  test-go-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Setup Kubernetes hosts for tests
        run: |
          sudo echo "127.0.0.1 127.0.0.1.default.svc.cluster.local 127.0.0.1.test.svc.cluster.local" | sudo tee -a /etc/hosts

      - name: Install Dependencies
        run: go get -v -t -d ./...

      - name: Test Go Code
        run: go test -cover ./pkg/...
