name: Vulnerability Scan

on:
  release:
    types: [ created ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: build local container
      uses: docker/build-push-action@v4
      with:
        tags: docker.io/guardgress:1.0.0-dev
        push: false
        load: true

    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: "docker.io/guardgress:1.0.0-dev"